.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH bencher 1  "bencher 0.2.28" 
.SH NAME
bencher \- Bencher CLI
.SH SYNOPSIS
\fBbencher\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Bencher CLI
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information
.SH SUBCOMMANDS
.TP
bencher\-auth(1)
Server authentication & authorization
.TP
bencher\-organization(1)
Manage organization
.TP
bencher\-member(1)
Manage organization members
.TP
bencher\-project(1)
Manage projects
.TP
bencher\-report(1)
Manage reports
.TP
bencher\-result(1)
View results
.TP
bencher\-branch(1)
Manage branches
.TP
bencher\-testbed(1)
Manage testbeds
.TP
bencher\-threshold(1)
Manage thresholds
.TP
bencher\-metric\-kind(1)
Manage metric kinds
.TP
bencher\-run(1)
Run benchmarks
.TP
bencher\-benchmark(1)
View benchmarks
.TP
bencher\-alert(1)
View alerts
.TP
bencher\-perf(1)
Query benchmark data
.TP
bencher\-user(1)
View user
.TP
bencher\-token(1)
Manage user API tokens
.TP
bencher\-server(1)
Server commands
.TP
bencher\-mock(1)
Generate mock benchmark data
.TP
bencher\-help(1)
Print this message or the help of the given subcommand(s)
.SH VERSION
v0.2.28
.SH AUTHORS
Everett Pompeii <epompeii@protonmail.com>
