#!/bin/sh

# Format Rust code
cargo fmt

# Format JS code
cd services/console && npx biome format --write . && cd -
cd services/action && npx biome format --write . && cd -

# If there was a change/the git tree is diry add all updated files and commit
git diff --quiet || git add .