#!/bin/sh

# Format Rust code
cargo fmt

# Format JS code
cd services/ui && npx rome format --write . && cd -
cd services/console && npx rome format --write . && cd -
cd services/action && npx rome format --write . && cd -

# If there was a change/the git tree is diry add all updated files and commit
git diff --quiet || git add .