DROP INDEX IF EXISTS index_project_organization_created;
DROP INDEX IF EXISTS index_report_project_created;
DROP INDEX IF EXISTS index_plot_project_created;
DROP INDEX IF EXISTS index_branch_project_created;
DROP INDEX IF EXISTS index_head_branch_created;
DROP INDEX IF EXISTS index_testbed_project_created;
DROP INDEX IF EXISTS index_benchmark_project_created;
DROP INDEX IF EXISTS index_measure_project_created;
DROP INDEX IF EXISTS index_threshold_project_created;
DROP INDEX IF EXISTS index_model_threshold_created;
CREATE INDEX index_project_organization_created ON project(organization_id, created);
CREATE INDEX index_report_project_created ON report(project_id, created);
CREATE INDEX index_plot_project_created ON plot(project_id, created);
CREATE INDEX index_branch_project_created ON branch(project_id, created);
CREATE INDEX index_head_branch_created ON head(branch_id, created);
CREATE INDEX index_testbed_project_created ON testbed(project_id, created);
CREATE INDEX index_benchmark_project_created ON benchmark(project_id, created);
CREATE INDEX index_measure_project_created ON measure(project_id, created);
CREATE INDEX index_threshold_project_created ON threshold(project_id, created);
CREATE INDEX index_model_threshold_created ON model(threshold_id, created);