[package]
name = "bencher_callback"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false

[features]
default = []
# Required due to feature unification
# https://doc.rust-lang.org/cargo/reference/features.html#feature-unification
plus = ["dep:aws-lc-rs", "dep:bencher_json", "dep:thiserror", "dep:uuid"]
db = ["dep:diesel", "diesel/sqlite"]

[dependencies]
aws-lc-rs = { workspace = true, optional = true }
bencher_json = { workspace = true, optional = true, features = ["plus", "server"] }
diesel = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
uuid = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions.workspace = true

[lints]
workspace = true
