[package]
name = "bencher_oci_storage"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false

[features]
default = []
test-clock = ["bencher_json?/test-clock"]
# Required due to feature unification
# https://doc.rust-lang.org/cargo/reference/features.html#feature-unification
plus = [
    "dep:bencher_json",
    "dep:bytes",
    "dep:chrono",
    "dep:futures",
    "dep:hex",
    "dep:http",
    "dep:hyper",
    "dep:object_store",
    "dep:serde",
    "dep:serde_json",
    "dep:sha2",
    "dep:slog",
    "dep:sync_wrapper",
    "dep:thiserror",
    "dep:tokio",
    "dep:uuid",
]
sentry = ["dep:sentry"]
otel = []

[dependencies]
# Bencher internal crates
bencher_json = { workspace = true, optional = true, features = ["server", "plus"] }

sentry = { workspace = true, optional = true }

# External dependencies
bytes = { workspace = true, optional = true }
chrono = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
hex = { workspace = true, optional = true }
http = { workspace = true, optional = true }
hyper = { workspace = true, optional = true }
object_store = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
sha2 = { workspace = true, optional = true }
slog = { workspace = true, optional = true }
sync_wrapper = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
tokio = { workspace = true, optional = true, features = ["rt"] }
uuid = { workspace = true, optional = true, features = ["v4"] }

[dev-dependencies]
bencher_json = { workspace = true, features = ["server", "plus", "test-clock"] }
http-body-util.workspace = true
reqwest = { workspace = true, features = ["blocking"] }
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "time"] }

[lints]
workspace = true
