-- This file should undo anything in `up.sql`
DROP TABLE alert;
DROP TABLE threshold;
DROP TABLE statistic;
DROP TABLE perf;
DROP TABLE resource;
DROP TABLE throughput;
DROP TABLE latency;
DROP TABLE report;
DROP TABLE benchmark;
DROP TABLE testbed;
DROP TABLE version;
DROP TABLE branch;
DROP TABLE project_role;
DROP TABLE project;
DROP TABLE organization_role;
DROP TABLE organization;
DROP TABLE token;
DROP TABLE user;