DROP INDEX IF EXISTS index_branch_head_id;
DROP INDEX IF EXISTS index_job_organization;
DROP INDEX IF EXISTS index_job_runner_id;
CREATE INDEX index_job_runner_id ON job(runner_id)
WHERE runner_id IS NOT NULL;
DROP INDEX IF EXISTS index_metric_measure;
DROP INDEX IF EXISTS index_organization_role_organization;
DROP INDEX IF EXISTS index_plot_benchmark_benchmark;
DROP INDEX IF EXISTS index_plot_branch_branch;
DROP INDEX IF EXISTS index_plot_measure_measure;
DROP INDEX IF EXISTS index_plot_testbed_testbed;
DROP INDEX IF EXISTS index_project_key_creator;
DROP INDEX IF EXISTS index_project_role_project;
DROP INDEX IF EXISTS index_report_user;
DROP INDEX IF EXISTS index_sso_organization;
DROP INDEX IF EXISTS index_threshold_measure;
DROP INDEX IF EXISTS index_threshold_testbed;
DROP INDEX IF EXISTS index_version_project;
