name: Nix

on:
  workflow_dispatch:
  push:
    branches: [devel, cloud]
    tags: [v**]
  pull_request:
    branches: [main, cloud, devel]

# Cancel in-progress runs for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Detect Changes
    if: github.ref != 'refs/heads/cloud'
    runs-on: ubuntu-22.04
    outputs:
      nix: ${{ steps.filter.outputs.nix }}
      cli: ${{ steps.filter.outputs.cli }}
      api: ${{ steps.filter.outputs.api }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            nix:
              - 'flake.nix'
              - 'flake.lock'
              - '.github/workflows/nix.yml'
            cli:
              - 'services/cli/**'
              - 'lib/bencher_adapter/**'
              - 'lib/bencher_client/**'
              - 'lib/bencher_comment/**'
              - 'lib/bencher_context/**'
              - 'lib/bencher_json/**'
              - 'lib/bencher_noise/**'
              - 'lib/bencher_parser/**'
              - 'lib/bencher_valid/**'
            api:
              - 'services/api/**'
              - 'lib/api_auth/**'
              - 'lib/api_checkout/**'
              - 'lib/api_organizations/**'
              - 'lib/api_projects/**'
              - 'lib/api_run/**'
              - 'lib/api_server/**'
              - 'lib/api_users/**'
              - 'lib/bencher_adapter/**'
              - 'lib/bencher_boundary/**'
              - 'lib/bencher_config/**'
              - 'lib/bencher_context/**'
              - 'lib/bencher_endpoint/**'
              - 'lib/bencher_json/**'
              - 'lib/bencher_logger/**'
              - 'lib/bencher_plot/**'
              - 'lib/bencher_rank/**'
              - 'lib/bencher_rbac/**'
              - 'lib/bencher_schema/**'
              - 'lib/bencher_token/**'
              - 'lib/bencher_valid/**'
              - 'plus/api_oci/**'
              - 'plus/api_runners/**'
              - 'plus/api_specs/**'
              - 'plus/bencher_billing/**'
              - 'plus/bencher_bing_index/**'
              - 'plus/bencher_github_client/**'
              - 'plus/bencher_google_client/**'
              - 'plus/bencher_google_index/**'
              - 'plus/bencher_license/**'
              - 'plus/bencher_oci_storage/**'
              - 'plus/bencher_otel/**'
              - 'plus/bencher_otel_provider/**'
              - 'plus/bencher_recaptcha/**'

  nix_lints:
    name: Check nix code
    needs: changes
    if: ${{ needs.changes.outputs.nix == 'true' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-25.11
      - name: Check nix formatting
        run: nix develop .#ci --command alejandra --check .
      - name: Check nix lints
        run: nix develop .#ci --command statix check
      - name: Check for dead nix code
        run: nix develop .#ci --command deadnix

  build_bencher_nix:
    name: Build `bencher` Nix Package
    needs: changes
    if: ${{ needs.changes.outputs.nix == 'true' || needs.changes.outputs.cli == 'true' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-25.11
      - name: Nix build
        run: nix build .#bencher

  build_api_nix:
    name: Build `api` Nix Package
    needs: changes
    if: ${{ needs.changes.outputs.nix == 'true' || needs.changes.outputs.api == 'true' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-25.11
      - name: Nix build
        run: nix build .#api
