name: Rebase cloud on devel

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rebase_cloud_on_devel:
    name: Rebase cloud on devel
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Rebase cloud on devel
        run: |
          set -euo pipefail
          git config --global user.name "Bencher"
          git config --global user.email "git@bencher.dev"
          git fetch origin devel cloud
          git checkout cloud
          git rebase origin/devel
          git push
