name: Track Benchmarks

on:
  workflow_call:
    secrets:
      BENCHER_API_TOKEN:
        required: true
      BENCHER_USER_EMAIL:
        required: true

jobs:
  track_benchmarks:
    name: Track Benchmarks with Bencher
    permissions:
      checks: write
    runs-on: ubuntu-22.04
    steps:
      - name: Download Noise Results (ubuntu)
        uses: actions/download-artifact@v8
        with:
          name: noise_results_ubuntu-22.04
      - name: Download Noise Results (macos)
        uses: actions/download-artifact@v8
        with:
          name: noise_results_macos-14
      - name: Download Noise Results (windows)
        uses: actions/download-artifact@v8
        with:
          name: noise_results_windows-2022
      - name: Download Bench Image
        id: download_bench
        continue-on-error: true
        uses: actions/download-artifact@v8
        with:
          name: bench_image.tar
      - name: Load and push image
        if: steps.download_bench.outcome == 'success'
        run: |
          docker load -i bench_image.tar
          echo '${{ secrets.BENCHER_API_TOKEN }}' | docker login registry.bencher.dev -u '${{ secrets.BENCHER_USER_EMAIL }}' --password-stdin
          docker push registry.bencher.dev/bencher:${{ github.sha }}
      - uses: bencherdev/bencher@main
      - name: Track Noise (ubuntu)
        run: |
          bencher run \
          --project bencher \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch ${{ github.ref_name }} \
          --hash '${{ github.sha }}' \
          --testbed ubuntu-22.04 \
          --threshold-measure noise-score \
          --threshold-test t_test \
          --threshold-max-sample-size 64 \
          --threshold-upper-boundary 0.9999 \
          --thresholds-reset \
          --adapter json \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          --ci-only-on-alert \
          --file ./noise_results_ubuntu-22.04.json
      - name: Track Noise (macos)
        run: |
          bencher run \
          --project bencher \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch ${{ github.ref_name }} \
          --hash '${{ github.sha }}' \
          --testbed macos-14 \
          --threshold-measure noise-score \
          --threshold-test t_test \
          --threshold-max-sample-size 64 \
          --threshold-upper-boundary 0.9999 \
          --thresholds-reset \
          --adapter json \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          --ci-only-on-alert \
          --file ./noise_results_macos-14.json
      - name: Track Noise (windows)
        run: |
          bencher run \
          --project bencher \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch ${{ github.ref_name }} \
          --hash '${{ github.sha }}' \
          --testbed windows-2022 \
          --threshold-measure noise-score \
          --threshold-test t_test \
          --threshold-max-sample-size 64 \
          --threshold-upper-boundary 0.9999 \
          --thresholds-reset \
          --adapter json \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          --ci-only-on-alert \
          --file ./noise_results_windows-2022.json
      - name: Track benchmarks with Bencher
        if: steps.download_bench.outcome == 'success'
        run: |
          bencher run \
          --project bencher \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --image "bencher:${{ github.sha }}" \
          --branch ${{ github.ref_name }} \
          --hash '${{ github.sha }}' \
          --testbed intel-v1 \
          --spec intel-v1 \
          --threshold-measure latency \
          --threshold-test t_test \
          --threshold-max-sample-size 64 \
          --threshold-upper-boundary 0.9999 \
          --thresholds-reset \
          --error-on-alert \
          --adapter rust_criterion \
          --github-actions '${{ secrets.GITHUB_TOKEN }}'
