name: Track PR Benchmarks

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  track_pr_benchmarks:
    name: Track PR Benchmarks with Bencher
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    permissions:
      pull-requests: write
    runs-on: ubuntu-22.04
    env:
      PR_EVENT: event.json
    steps:
      - name: Download Noise Results (ubuntu)
        uses: dawidd6/action-download-artifact@v6
        with:
          name: noise_results_ubuntu-22.04
          run_id: ${{ github.event.workflow_run.id }}
      - name: Download Noise Results (macos)
        uses: dawidd6/action-download-artifact@v6
        with:
          name: noise_results_macos-14
          run_id: ${{ github.event.workflow_run.id }}
      - name: Download Noise Results (windows)
        uses: dawidd6/action-download-artifact@v6
        with:
          name: noise_results_windows-2022
          run_id: ${{ github.event.workflow_run.id }}
      - name: Download PR Event
        uses: dawidd6/action-download-artifact@v6
        with:
          name: ${{ env.PR_EVENT }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Read PR Event Data
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const prEvent = JSON.parse(fs.readFileSync(process.env.PR_EVENT, 'utf8'));
            core.exportVariable('PR_HEAD', prEvent.pull_request.head.ref);
            core.exportVariable('PR_HEAD_SHA', prEvent.pull_request.head.sha);
            core.exportVariable('PR_BASE', prEvent.pull_request.base.ref);
            core.exportVariable('PR_BASE_SHA', prEvent.pull_request.base.sha);
            core.exportVariable('PR_NUMBER', prEvent.number);
      - name: Download Bench Image
        id: download_bench
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v6
        with:
          name: bench_image.tar
          run_id: ${{ github.event.workflow_run.id }}
      - name: Load and push image
        id: load_push
        if: steps.download_bench.outcome == 'success'
        continue-on-error: true
        run: |
          docker load -i bench_image.tar
          docker tag bench:ci registry.bencher.dev/bencher:${{ github.event.workflow_run.head_sha }}
          echo '${{ secrets.BENCHER_API_TOKEN }}' | docker login registry.bencher.dev -u '${{ secrets.BENCHER_USER_EMAIL }}' --password-stdin
          docker push registry.bencher.dev/bencher:${{ github.event.workflow_run.head_sha }}
      - uses: bencherdev/bencher@main
      - name: Track Noise (ubuntu)
        env:
          BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
        run: |
          bencher run \
          --project bencher \
          --token "$BENCHER_API_TOKEN" \
          --branch "$PR_HEAD" \
          --hash "$PR_HEAD_SHA" \
          --start-point "$PR_BASE" \
          --start-point-hash "$PR_BASE_SHA" \
          --start-point-clone-thresholds \
          --start-point-reset \
          --testbed ubuntu-22.04 \
          --adapter json \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          --ci-only-on-alert \
          --ci-number "$PR_NUMBER" \
          --file ./noise_results_ubuntu-22.04.json
      - name: Track Noise (macos)
        env:
          BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
        run: |
          bencher run \
          --project bencher \
          --token "$BENCHER_API_TOKEN" \
          --branch "$PR_HEAD" \
          --hash "$PR_HEAD_SHA" \
          --start-point "$PR_BASE" \
          --start-point-hash "$PR_BASE_SHA" \
          --start-point-clone-thresholds \
          --start-point-reset \
          --testbed macos-14 \
          --adapter json \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          --ci-only-on-alert \
          --ci-number "$PR_NUMBER" \
          --file ./noise_results_macos-14.json
      - name: Track Noise (windows)
        env:
          BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
        run: |
          bencher run \
          --project bencher \
          --token "$BENCHER_API_TOKEN" \
          --branch "$PR_HEAD" \
          --hash "$PR_HEAD_SHA" \
          --start-point "$PR_BASE" \
          --start-point-hash "$PR_BASE_SHA" \
          --start-point-clone-thresholds \
          --start-point-reset \
          --testbed windows-2022 \
          --adapter json \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          --ci-only-on-alert \
          --ci-number "$PR_NUMBER" \
          --file ./noise_results_windows-2022.json
      - name: Track Benchmarks with Bencher
        if: steps.load_push.outcome == 'success'
        env:
          BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
        run: |
          bencher run \
          --project bencher \
          --token "$BENCHER_API_TOKEN" \
          --image "bencher:${{ github.event.workflow_run.head_sha }}" \
          --branch "$PR_HEAD" \
          --hash "$PR_HEAD_SHA" \
          --start-point "$PR_BASE" \
          --start-point-hash "$PR_BASE_SHA" \
          --start-point-clone-thresholds \
          --start-point-reset \
          --testbed intel-v1 \
          --spec intel-v1 \
          --adapter rust_criterion \
          --error-on-alert \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          --ci-number "$PR_NUMBER"
      - name: Check image push
        if: steps.download_bench.outcome == 'success' && steps.load_push.outcome != 'success'
        run: exit 1
